import Head from 'next/head';
import { useRouter } from 'next/router';
import FormDetailRecipe from '../../../components/organisms/FormDetail';
import MainLayout from '../../../layouts/MainLayout';

function DetailRecipe() {
   const route = useRouter();
   const id_recipe = route?.query?.id;

   return (
      <div>
         <Head>
            <title>Ricette mobile - Detail Recipe</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <MainLayout>
            <FormDetailRecipe id={id_recipe} />
         </MainLayout>
      </div>
   );
}

export default DetailRecipe;
