import Head from 'next/head';
import FormPopular from '../../components/organisms/FormPopular';
import MainLayout from '../../layouts/MainLayout';

function home() {
  return (
    <div>
      <Head>
        <title>Form Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <MainLayout>
        <FormPopular />
      </MainLayout>
    </div>
  );
}

export default home;
