import Head from 'next/head';
import axios from 'axios';
import { API_URL } from '../../helper/env';

import FormPopular from '../../components/organisms/FormPopular';
import MainLayout from '../../layouts/MainLayout';

export async function getStaticProps() {
  const popularRecipe = await axios({
    method: 'GET',
    url: `${API_URL}recipe`,
  });
  return {
    props: {
      dataPopular: popularRecipe?.data.data,
    },
  };
}

function popularRecipe({ dataPopular }) {
  return (
    <div>
      <Head>
        <title>Form Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <FormPopular data={dataPopular} />
    </div>
  );
}

export default popularRecipe;
