/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable no-unused-vars */
import Head from 'next/head';
import axios from 'axios';
import alert from 'sweetalert2';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

import { API_URL } from '../../../helper/env';
import FormSearch from '../../../components/organisms/FormSearch';
import MainLayout from '../../../layouts/MainLayout';

export async function getServerSideProps(context) {
   try {
      const { search } = context.query;
      const res = await axios({
         method: 'GET',
         url: `${API_URL}search?search=${search}&limit=5`,
      });
      return {
         props: {
            data: res?.data?.data,
         },
      };
   } catch (err) {
      return {
         props: {
            data: err.response.data.data,
         },
      };
   }
}

function search({ data }) {
   const router = useRouter();

   useEffect(() => {
      if (data <= 0) {
         alert.fire({
            title: 'Failed',
            text: 'Data not found',
            icon: 'Error',
         });
         router.push('/');
      }
   }, [data]);
   return (
      <div>
         <Head>
            <title>Ricette mobile - Search</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <MainLayout>
            <FormSearch data={data} />
         </MainLayout>
      </div>
   );
}

export default search;
