/* eslint-disable no-unused-vars */
import Head from 'next/head';
import axios from 'axios';
import { API_URL } from '../../../helper/env';
import FormSearch from '../../../components/organisms/FormSearch';
import MainLayout from '../../../layouts/MainLayout';

export async function getServerSideProps(context) {
   const { search } = context.query;
   const response = await axios({
      method: 'GET',
      url: `${API_URL}search/${search}`,
   });
   return {
      props: {
         data: response?.data?.data,
      },
   };
}

function search({ data }) {
   return (
      <div>
         <Head>
            <title>Search</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <MainLayout>
            <FormSearch data={data} />
         </MainLayout>
      </div>
   );
}

export default search;
