import Head from 'next/head';
import FormSearch from '../../../components/organisms/FormSearch';
import MainLayout from '../../../layouts/MainLayout';
import axios from 'axios';

export async function getServerSideProps(context) {
  const { search } = context.query;
  const response = await axios({
    method: 'GET',
    url: `http://localhost:8120/search/${search}`,
  });
  return {
    props: {
      data: response?.data?.data,
    },
  };
}

function search({ data }) {
  return (
    <div>
      <Head>
        <title>Form Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <MainLayout>
        <FormSearch data={data} />
      </MainLayout>
    </div>
  );
}

export default search;
