/* eslint-disable no-unused-vars */
import Head from 'next/head';
import axios from 'axios';
import { API_URL } from '../../../helper/env';

import FormPopular from '../../../components/organisms/FormPopular';
import MainLayout from '../../../layouts/MainLayout';

export async function getServerSideProps(context) {
   try {
      const { page } = context.query;
      const response = await axios({
         method: 'GET',
         url: `${API_URL}recipes?limit=5&page=${page}&type=ASC`,
      });
      const data = response.data.data;
      if (data == undefined) {
         return {
            redirect: {
               destination: '/',
               permanent: false,
            },
         };
      } else {
         return {
            props: {
               dataPopular: data,
            },
         };
      }
   } catch (err) {
      return {
         props: {
            data: err.response.data.data,
         },
      };
   }
}

function popularRecipe({ dataPopular }) {
   return (
      <div>
         <Head>
            <title>Ricette mobile - Form Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <MainLayout>
            <FormPopular data={dataPopular} />
         </MainLayout>
      </div>
   );
}

export default popularRecipe;
