/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/rules-of-hooks */
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Loading from 'react-content-loader';
import axios from '../../../helper/axios';

import FormVideo from '../../../components/organisms/FormVideo';
import MainLayout from '../../../layouts/MainLayout';
import { useRouter } from 'next/router';

function video() {
   const router = useRouter();
   const id = router?.query?.id;
   const [loading, setLoading] = useState(false);
   const [data, setData] = useState([]);

   useEffect(() => {
      getRecipe();
   }, [id]);

   const getRecipe = () => {
      setLoading(true);
      axios
         .get(`recipe/${id}`)
         .then((res) => {
            setData(res?.data?.data);
            setLoading(false);
         })
         .catch((err) => {
            err?.response;
            console.log(err?.response?.data?.message);
            setLoading(false);
         });
   };
   return (
      <div>
         <Head>
            <title>Ricette mobile - Recipe Video</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <MainLayout>
            {loading ? <Loading /> : <FormVideo data={data} />}
         </MainLayout>
      </div>
   );
}

export default video;
