import Head from 'next/head';
import FormForgot from '../../components/organisms/FormForgot';

function forgot() {
   return (
      <div>
         <Head>
            <title>Ricette mobile - Form Forgot</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <FormForgot />
      </div>
   );
}

export default forgot;
