import Head from 'next/head';
import FormForget from '../../components/organisms/FormForget';

function forget() {
  return (
    <div>
      <Head>
        <title>Form Forget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <FormForget />
    </div>
  );
}

export default forget;
