import Head from 'next/head';
import FormRegister from '../../components/organisms/FormRegister';

function Register() {
   return (
      <div>
         <Head>
            <title>Ricette mobile - Form Register</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <FormRegister />
      </div>
   );
}

export default Register;
