import Head from 'next/head';
import FormMyRecipe from '../../components/organisms/FormMyRecipe';
import MainLayout from '../../layouts/MainLayout';
import axios from 'axios';

export async function getStaticProps() {
  const recipe = await axios({
    method: 'GET',
    url: 'http://localhost:8120/recipe',
  });
  return {
    props: {
      data: recipe?.data.data,
    },
  };
}

function myRecipe({ data }) {
  return (
    <div>
      <Head>
        <title>Form Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <FormMyRecipe data={data} />
    </div>
  );
}

export default myRecipe;
