import Head from 'next/head';
import React from 'react';
import FormProfile from '../../components/organisms/FormProfile';
import MainLayout from '../../layouts/MainLayout';

function profile() {
   return (
      <div>
         <Head>
            <title>Ricette mobile - Form Profile</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <MainLayout>
            <FormProfile />
         </MainLayout>
      </div>
   );
}

export default profile;
