import Head from 'next/head';
import FormUpdate from '../../components/organisms/FormUpdate';
// import MainLayout from '../../layouts/MainLayout';

function update() {
  return (
    <div>
      <Head>
        <title>Edit Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <FormUpdate />
    </div>
  );
}

export default update;
