import Head from 'next/head';
import axios from 'axios';
import { API_URL } from '../../../helper/env';
import FormMyRecipe from '../../../components/organisms/FormMyRecipe';

export async function getServerSideProps(context) {
   try {
      const { me } = context.query;
      const response = await axios({
         method: 'GET',
         url: `${API_URL}myrecipe/${me}`,
      });
      return {
         props: {
            data: response?.data?.data,
         },
      };
   } catch (err) {
      return {
         props: {
            data: err.response.data.data,
         },
      };
   }
}

function myRecipe({ data }) {
   return (
      <div>
         <Head>
            <title>Ricette mobile - My Recipe</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <FormMyRecipe data={data} />
      </div>
   );
}

export default myRecipe;
