import Head from 'next/head';
import FormMyRecipe from '../../../components/organisms/FormMyRecipe';
import axios from 'axios';
import { API_URL } from '../../../helper/env';

export async function getServerSideProps(context) {
   const { me } = context.query;
   const response = await axios({
      method: 'GET',
      url: `${API_URL}myrecipe/${me}`,
   });
   return {
      props: {
         data: response?.data?.data,
      },
   };
}

function myRecipe({ data }) {
   return (
      <div>
         <Head>
            <title>Form Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
         </Head>
         <FormMyRecipe data={data} />
      </div>
   );
}

export default myRecipe;
