import Head from 'next/head'
import Slider from  '../components/molecules/SlideRecipe'
import Popular from  '../components/molecules/SlidePopular'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>recitte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
        <Slider />
        {/* <Popular /> */}
    </div>
  )
}
