import Head from 'next/head'
import FormHome from '../components/organisms/FormHome'

function home() {
  return (
    <div>
      <Head>
        <title>Form Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <FormHome />
    </div>
  )
}

export default home