import Head from 'next/head';
import Search from '../components/molecules/Search';
import Slider from '../components/molecules/SlideRecipe';
import Popular from '../components/molecules/SlidePopular';
import NavBar from '../components/atoms/Navbar';
import axios from 'axios';

export async function getStaticProps() {
  const newRecipe = await axios({
    method: 'GET',
    url: 'http://localhost:8120/recipe/latest',
  });
  const popularRecipe = await axios({
    method: 'GET',
    url: 'http://localhost:8120/recipe',
  });
  return {
    props: {
      dataNew: newRecipe?.data?.data,
      dataPopular: popularRecipe?.data.data,
    },
  };
}

function home({ dataNew, dataPopular }) {
  return (
    <div>
      <Head>
        <title>Form Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Search />
      <Slider data={dataNew} />
      <Popular data={dataPopular} />
      <NavBar />
    </div>
  );
}

export default home;
